### PR TITLE
fix: issue 1071

### PR DESCRIPTION
**Pull request by narekcat**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@narekcat great finding.

It works good, just would like to improve one moment. Currenlty, when we select user the width of the field jumps, see demo video https://monosnap.com/file/BvqGuMNIyLfJG2ytnsELQaKPFnKxQM

Can we fix it so it doesn't jump when we select the user or clear it?

Another thing, could you please pull the latest changes from `develop` branch. Your fix is done for some outdated version, just to make sure it works good with the latest code we have in the `develop` branch now.

Thanks

**Comment by narekcat** [comment]
Hi @maxceem . I'll fix both issues and update pull request.

**Comment by narekcat** [comment]
@maxceem . I have updated pull request.

**Review by maxceem — APPROVED** [review]
Works prefectly now @narekcat.

**Pull request merged**
