### PR TITLE
add Iterative Reviewer for First2Finish and Task type challenges

### PR DESCRIPTION
**Pull request by kodar007**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks, @kodar007. I've noticed a couple small issues:

1. After page reloading the selected reviwer is not shown in the field anymore:

   image
   
2. If I select the same reviewer again and click Save I would get error:

     image

Note, that we don't have such issues for the challenge type `Challenge` which uses role `Reviewer`.

**Comment by kodar007** [comment]
@maxceem done, could you please adjust prize to incorporate fix for point 1 above?

**Review by maxceem — CHANGES_REQUESTED** [review]
@kodar007 prize update to cover the requirement to show the selected reviewer.

Though at the moment it doesn't work for me.

If I create a new task, set internal reviewer, choose user and click Save, I would get an error:

   image
   
And after reloading the user would not be shown as selected.

**Comment by kodar007** [comment]
@maxceem just now noticed, working on it

**Review by maxceem — APPROVED** [review]
Thanks, @kodar007. Works good now.

**Pull request merged**
