### PR TITLE
fix issue-#1058

### PR DESCRIPTION
**Pull request by mark-nakachon**

### CODE REVIEW

**Comment by vikasrohit** [comment]
Thanks @mark-nakachon for the PR. @maxceem is out for couple of days, he would do the detailed review when he is back. However, meanwhile when I tried your PR on my local, it worked great and as per my expectations with only weird case where when I set `beta=true` on `/projects/{projectId}/challenges` page then I am able to unset the beta mode only when I am on the same page i.e. I am not able to unset beta mode on `/projects/{projectId}/challenges/{challengeId}/view` or `/projects/{projectId}/challenges/{challengeId}/edit`. While in reverse case when I am set beta mode on `/projects/{projectId}/challenges/{challengeId}/view` or `/projects/{projectId}/challenges/{challengeId}/edit`, I am able to unset it from `/projects/{projectId}/challenges`.

**Comment by mark-nakachon** [comment]
@vikasrohit it's a path issue it's fixed now, Can you try again now

**Comment by vikasrohit** [comment]
@mark-nakachon it works now. Thanks. @maxceem I am merging the PR for now ahead of demo, please review the PR once you are back. I didn't see any specific issue with the PR.

**Comment by maxceem** [comment]
@vikasrohit @mark-nakachon I did the review of this PR and it looks great for me.

**Pull request merged**
