### PR TITLE
Issue 1019

### PR DESCRIPTION
**Pull request by yoution**
image

### CODE REVIEW

**Comment by vikasrohit** [comment]
@yoution I guess we need to check if the API can return us challenges with multiple statuses because `Cancelled` tab would list all challenges which are cancelled with various [cancel statuses](https://github.com/topcoder-platform/work-manager/blob/develop/src/config/constants.js#L241).

**Comment by yoution** [comment]
@vikasrohit 
it return all of the status
image

image

**Comment by vikasrohit** [comment]
Awesome. I was worried about it. Thanks for confirming.

**Comment by vikasrohit** [comment]
@phead198708 @yoution I have updated the base to `https://github.com/topcoder-platform/work-manager/tree/feature/bug-bash-july` instead of `bug-bash-june`.

**Pull request merged**
