### PR TITLE
added assign to me button

### PR DESCRIPTION
**Pull request by nursoltan-s**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@nursoltan-s works good, but there was one small requirement update, instead of a button we have to add a smile blue hyperlink, see https://github.com/topcoder-platform/work-manager/issues/1017#issuecomment-754600319. Could you please, replace the button with a simple hyperlink so it doesn't take so much attention.

**Comment by nursoltan-s** [comment]
@maxceem changed button to hyperlink

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks for the quick update @nursoltan-s.

When we click the link, then `#` is added to the URL. Can we avoid it to keep things clear?

image

**Comment by nursoltan-s** [comment]
@maxceem updated.

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks, @nursoltan-s link is good now. But noticed one more thing, we should not show this link on the view page, only during editing:

image

**Comment by nursoltan-s** [comment]
@maxceem updated

**Review by maxceem — CHANGES_REQUESTED** [review]
@nursoltan-s it looks like we already have a flag that can be used to detect if we are in Edit or View mode, called `readOnly`. We set it in view mode https://github.com/topcoder-platform/work-manager/blob/cf-jan-2021/src/components/ChallengeEditor/ChallengeView/index.js#L138. So it could be used to hide the `assign me` link, and we don't have to add a new flag `isEdit`.

**Comment by nursoltan-s** [comment]
> @nursoltan-s it looks like we already have a flag that can be used to detect if we are in Edit or View mode, called `readOnly`. We set it in view mode https://github.com/topcoder-platform/work-manager/blob/cf-jan-2021/src/components/ChallengeEditor/ChallengeView/index.js#L138. So it could be used to hide the `assign me` link, and we don't have to add a new flag `isEdit`.

But. `readOnly` flag was set to false on both pages(edit and view pages)

**Comment by maxceem** [comment]
@nursoltan-s hmm, it's `true` for me.

The next line `<AssignedMemberField challenge={challenge} assignedMemberDetails={assignedMemberDetails} readOnly />` is equal to `<AssignedMemberField challenge={challenge} assignedMemberDetails={assignedMemberDetails} readOnly={true} />`.

image

**Comment by nursoltan-s** [comment]
@maxceem sorry. Updated the brand. Can you please check now?

**Review by maxceem — APPROVED** [review]
Thanks for the quick updates @nursoltan-s. All perfect now.

**Pull request merged**
