### PR TITLE
fix: issue #1205

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by vikasrohit** [comment]
@yoution thanks for the PR, however, just curious what caused the specific track's challenge forum URL to not work? I mean you removed the map operation and instead used lodash to directly access the 0th discussion url. How did it made the difference?

**Comment by yoution** [comment]
@vikasrohit 
1. what caused the specific track's challenge forum URL to not work? 
    because BE not return the `url` field, currently if Be not return the `url` field, just hide the `forum` link
image

2.why do I remove the map opetation?
becase I think one  challenge only has one forum at most, so it 's  not necessory to use `map operation`

**Comment by vikasrohit** [comment]
Thanks for the detailed explanation @yoution. So it means we still not have a working forums link for Data Science challenges. We would rather hide the `Forums` link, right?

**Comment by yoution** [comment]
@vikasrohit I donot know whether it work for Data Science challenges, If BE return `url` field ,  the `Forum` link will work, 
if not return `url` field, hide the link

**Comment by vikasrohit** [comment]
Ok, thanks @yoution however, I am afraid that the problem mentioned originally in the issue still persist. We need to fix the issue why Forums link is not there for data science tracks. If it is because backend system is not generating the forums, we need to delegate this issue to that team instead of hiding the forums link which I think would confuse people more.

**Comment by vikasrohit** [comment]
@yoution @phead198708 I am not merging this PR for now as we have to fix the root cause of missing Forums link for Data science. Closing the PR for now so that no one accidentally merge it. We can later recreate it if needed.

**Pull request closed without merging**
