### PR TITLE
issue-1083

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by yoution** [comment]
@bug-bash-helper https://github.com/topcoder-platform/work-manager/pull/1090 is ready for review

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution All good, but could we please slightly update the style, so it's easier to see the main error like this:

image

- alight left
- font size of error 25px
- add word `Error:` before the error message

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution sorry if I was not clear.

I mean keep the black title `There was an error loading the challenge`. And show the big error message inside the rectangle. So to make it the same like on the screenshot:

image

**Review by maxceem — APPROVED** [review]
Thank you for all the updates @yoution. Looks perfect now.

**Pull request merged**
